services:
  balise-sdk-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile.jar
    image: adiarra/balise-sdk-service:latest
    container_name: balise-sdk-service
    ports:
      - "6062:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://balise-postgres:5432/balisedb
      - SPRING_DATASOURCE_USERNAME=adminbdb
      - SPRING_DATASOURCE_PASSWORD=To7Z2UCeWTsriPxbADX8
      - SPRING_PROFILES_ACTIVE=backend
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - balise-postgres

  balise-tcp-server:
    image: adiarra/maxvision-enhanced:v1.0
    container_name: balise-tcp-server
    pull_policy: always
    ports:
      - "6060:6060"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - JAVA_OPTS=-Xmx512m -Xms256m
      - DB_URL=jdbc:postgresql://balise-postgres:5432/balisedb
      - DB_USER=adminbdb
      - DB_PASSWORD=To7Z2UCeWTsriPxbADX8
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 6060 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - balise-postgres

  balise-web-ui:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    image: adiarra/balise-web-ui:latest
    container_name: balise-web-ui
    ports:
      - "6061:80"
    depends_on:
      - balise-sdk-service

  cmacgm-integration:
    build:
      context: ./cma-cgm
      dockerfile: docker/Dockerfile.standalone
    image: adiarra/cmacgm-integration:latest
    container_name: cmacgm-integration
    ports:
      - "6064:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://balise-postgres:5432/balisedb
      - SPRING_DATASOURCE_USERNAME=adminbdb
      - SPRING_DATASOURCE_PASSWORD=To7Z2UCeWTsriPxbADX8
      - CMACGM_AUTH_URL=https://auth-pre.cma-cgm.com/as/token.oauth2
      - CMACGM_API_BASE_URL=https://apis-uat.cma-cgm.net/technical/generic/eagle/v1
      - CMACGM_CLIENT_ID=beapp-sinigroup
      - CMACGM_CLIENT_SECRET=YChnAz1dI2gvr40BMOyQWIeYT83DdtitHYfDmGd04xG5llcugV9NvfeihE72s1cJ
      - CMACGM_SCOPE=tracking:write:be
      - SERVER_PORT=8081
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      - balise-postgres
      - balise-sdk-service

  balise-postgres:
    image: postgis/postgis:14-3.3
    container_name: balise-postgres
    ports:
      - "6063:5432"
    environment:
      - POSTGRES_USER=adminbdb
      - POSTGRES_PASSWORD=To7Z2UCeWTsriPxbADX8
      - POSTGRES_DB=balisedb
      # Directly set Postgres to use md5 authentication
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - ./database-setup/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adminbdb -d balisedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
