server:
  port: 6060

spring:
  datasource:
    url: jdbc:postgresql://balise-postgres:5432/balisedb
    username: adminbdb
    password: To7Z2UCeWTsriPxbADX8
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mvgateway:
  servers:
    - port: 6060
      encrypt: true
      name: maxvision

logging:
  config: classpath:logback-config.xml
