server:
  port: 6060
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fleetdb
    username: fleetuser
    password: fleetpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mvgateway:
  servers:
    - port: 8910
      encrypt: true
      name: maxvision

logging:
  config: classpath:logback-config.xml
